/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardWhatsappRouteImport } from './routes/dashboard.whatsapp'
import { Route as DashboardProdutoRouteImport } from './routes/dashboard.produto'
import { Route as DashboardPedidosRouteImport } from './routes/dashboard.pedidos'
import { Route as DashboardConfigRouteImport } from './routes/dashboard.config'
import { Route as DashboardClientesRouteImport } from './routes/dashboard.clientes'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp.webhook'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWhatsappRoute = DashboardWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProdutoRoute = DashboardProdutoRouteImport.update({
  id: '/produto',
  path: '/produto',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPedidosRoute = DashboardPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConfigRoute = DashboardConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientesRoute = DashboardClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/clientes': typeof DashboardClientesRoute
  '/dashboard/config': typeof DashboardConfigRoute
  '/dashboard/pedidos': typeof DashboardPedidosRoute
  '/dashboard/produto': typeof DashboardProdutoRoute
  '/dashboard/whatsapp': typeof DashboardWhatsappRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/clientes': typeof DashboardClientesRoute
  '/dashboard/config': typeof DashboardConfigRoute
  '/dashboard/pedidos': typeof DashboardPedidosRoute
  '/dashboard/produto': typeof DashboardProdutoRoute
  '/dashboard/whatsapp': typeof DashboardWhatsappRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/clientes': typeof DashboardClientesRoute
  '/dashboard/config': typeof DashboardConfigRoute
  '/dashboard/pedidos': typeof DashboardPedidosRoute
  '/dashboard/produto': typeof DashboardProdutoRoute
  '/dashboard/whatsapp': typeof DashboardWhatsappRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/analytics'
    | '/dashboard/clientes'
    | '/dashboard/config'
    | '/dashboard/pedidos'
    | '/dashboard/produto'
    | '/dashboard/whatsapp'
    | '/dashboard/'
    | '/api/public/whatsapp/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/analytics'
    | '/dashboard/clientes'
    | '/dashboard/config'
    | '/dashboard/pedidos'
    | '/dashboard/produto'
    | '/dashboard/whatsapp'
    | '/dashboard'
    | '/api/public/whatsapp/webhook'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/analytics'
    | '/dashboard/clientes'
    | '/dashboard/config'
    | '/dashboard/pedidos'
    | '/dashboard/produto'
    | '/dashboard/whatsapp'
    | '/dashboard/'
    | '/api/public/whatsapp/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/whatsapp': {
      id: '/dashboard/whatsapp'
      path: '/whatsapp'
      fullPath: '/dashboard/whatsapp'
      preLoaderRoute: typeof DashboardWhatsappRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/produto': {
      id: '/dashboard/produto'
      path: '/produto'
      fullPath: '/dashboard/produto'
      preLoaderRoute: typeof DashboardProdutoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pedidos': {
      id: '/dashboard/pedidos'
      path: '/pedidos'
      fullPath: '/dashboard/pedidos'
      preLoaderRoute: typeof DashboardPedidosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/config': {
      id: '/dashboard/config'
      path: '/config'
      fullPath: '/dashboard/config'
      preLoaderRoute: typeof DashboardConfigRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clientes': {
      id: '/dashboard/clientes'
      path: '/clientes'
      fullPath: '/dashboard/clientes'
      preLoaderRoute: typeof DashboardClientesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardClientesRoute: typeof DashboardClientesRoute
  DashboardConfigRoute: typeof DashboardConfigRoute
  DashboardPedidosRoute: typeof DashboardPedidosRoute
  DashboardProdutoRoute: typeof DashboardProdutoRoute
  DashboardWhatsappRoute: typeof DashboardWhatsappRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardClientesRoute: DashboardClientesRoute,
  DashboardConfigRoute: DashboardConfigRoute,
  DashboardPedidosRoute: DashboardPedidosRoute,
  DashboardProdutoRoute: DashboardProdutoRoute,
  DashboardWhatsappRoute: DashboardWhatsappRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
